[package]
name = "aula04"
version = "0.1.0"
authors = ["Felipe Ranzani <no@email>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.17"
regex = "1"